#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Wed Jun 09 17:44:14 CEST 2021
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto 53ef2f00c98645bbbc1e77af3e6f3800 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot SERIAL_TX_TB_behav xil_defaultlib.SERIAL_TX_TB -log elaborate.log"
xelab -wto 53ef2f00c98645bbbc1e77af3e6f3800 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot SERIAL_TX_TB_behav xil_defaultlib.SERIAL_TX_TB -log elaborate.log

